#!/usr/bin//env php
<?php

include "src/Dates/BirthDays.php";
$birthdate = "1993-03-19";
$days = new \Gusakov\Dates\BirthDays($birthdate);

$totalDays = $days ->findTotalDays();
echo "$birthdate : $totalDays\n";